name: Build wheels

on:
  # Manually trigger
  workflow_dispatch:
  # Or push a tag
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      # Uploaded result can be found in Actions -> <select run> -> Artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: pyclothoid-wheels
          path: ./wheelhouse/*.whl
